Add Error Prone to build
wala/WALA pull request #1128
Opened 2022-09-29 04:32 UTC by msridhar

We only run Error Prone on JDK 11 builds, as recent Error Prone releases do not run on JDK 8.  We also disable WARNING level checks for now, to reduce the noise in the build output (we get hundreds of WARNING-level messages from Error Prone, which we should try to fix gradually).

This PR also fixes all errors reported by Error Prone.

2022-09-29 14:48 UTC, msridhar commented on com.ibm.wala.scandroid/src/main/java/org/scandroid/util/AndroidAnalysisContext.java
> -  /**
Deleting since this method just calls itself in an infinite recursion.  Clearly no other code has been calling it

2022-09-29 14:48 UTC, msridhar commented on com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/loader/AstMethod.java
> -  public boolean hasCatchBlock() {
Deleting since this method just calls itself in an infinite recursion. Clearly no other code has been calling it

2022-09-30 00:00 UTC, liblit requested changes

2022-09-30 00:48 UTC, msridhar commented
Thanks for the careful review @liblit!  I believe I have addressed all of your comments.

2022-09-30 01:09 UTC, liblit approved these changes

2022-09-30 01:18 UTC, merged